### ISSUE TITLE
Gravestone holos not removing

### ISSUE THREAD

**Issue by Mutim** [AuroraInteractive/network-script-data#55] opened 2020-08-17 12:52 UTC
When you die, the gravestone is created correctly. 

If you die, leave the area, and don't come back, the head disappears, but not the hologram. 

![2020-08-17_07 50 30](https://user-images.githubusercontent.com/22847483/90398004-553f9780-e05e-11ea-966b-48686879b25a.png)

Get to this area with:
/ex teleport <location[-534,80,-12,mainland]>

**Comment by Ph4i1ur3** [comment] 2020-08-17 13:10
potential fix pushed.

**Comment by Ph4i1ur3** [comment] 2020-08-17 13:12
Duplicate of #54

**Closed by Ph4i1ur3** 2020-08-17 13:12 UTC
